### PR TITLE
Added sourcemap generation for hub and widget.

### PR DESCRIPTION
**Pull request by MrTarantula**
Thank you for your pull request!
By completing this pull request, you agree to the [Contributing License Agreement](https://github.com/ALM-Rangers/Yeoman-extension-code-generator/blob/master/.github/CLA.md).

Changes proposed in this pull request:
- Adds sourcemap file generation for hub and widget extensions. This makes in-browser debugging available out of the box. I don't know if this is desired but it's my preferred config.

@ALM-Rangers/Yeoman-extension-code-generator

### CODE REVIEW

**Comment by MrTarantula** [comment]
It looks like sourcemaps were set to be generated from `tsconfig.json` but removed in #16.

**Comment by MrTarantula** [comment]
I'll be closing this in a week if you don't want to merge.

**Comment by wpschaub** [comment]
@MrTarantula can you elaborate on why you'd like the source maps re-added? The team intentionally removed them and debating the value of the maps in the template code.

**Comment by MrTarantula** [comment]
I've created several extensions with this generator, and this is the one thing I always change before beginning development. I code, then push to TFS, then debug in Chrome. Having a sourcemap lets me see and set breakpoints in the TS instead of the transpiled JS. Here is more info about the [Webpack devtool](https://webpack.js.org/configuration/devtool/) config option.

**Review by wpschaub — COMMENTED** [review]
Based on feedback with .ts debugging, I'm approving the change. @mikaelkrief I'll let you do a sanity review and merge the PR.

**Review by wpschaub — APPROVED** [review]
Based on feedback with .ts debugging, I'm approving the change. @mikaelkrief I'll let you do a sanity review and merge the PR.

**Review by mikaelkrief — APPROVED** [review]

**Pull request merged**
